version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=database
    volumes:
      - pgdata_auth:/var/lib/postgresql/data/
volumes:
  pgdata_auth: